name: 'My custom action'
description: 'Be a composite action'
runs:
  using: "composite"
  steps:
    - env:
        GHARep: ${{ github.action_repository }}
        GHARef: ${{ github.action_ref }}
      run: |
        echo ${{ env.GHARep }}
        echo ${{ env.GHARef }}
      shell: bash
