name: 'My custom action'
description: 'Be a composite action'
runs:
  using: "composite"
  steps:
    - env:
        GHARep: ${{ github.workflow }}
        GHARef: ${{ github.ref }}
      run: |
        echo ${{ github.workflow }}
        echo ${{ github.ref }}
      shell: bash
